version: '3.0'

services:
  voice-gpt-app:
    image: voice-gpt-app
    container_name: voice-gpt-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
        - /dev/snd:/dev/snd
    environment:
      # OPENAI API CONFIG
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
      - "MODEL_NAME=text-davinci-003"

      # HOSTS OF SERVICES
      - "GPT_HOST=localhost:8080"
      - "LISTENER_HOST=localhost:8081"
      - "GUI_HOST=localhost:8082"
      - "TTS_HOST=localhost:5001"
      - "STT_HOST=localhost:5000"

      #POSTGRES CONFIG
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=#{POSTGRES_PASSWORD}'
      - "POSTGRES_HOST=jdbc:postgresql://postgres:5432/logs-db"

      # TRIGGER WORD DETECTION MODEL CONFIG
      - "ACCESS_KEY=bIyF3LaYYuARsCmzGSd66gG06eb5NN1hBT2v3hcrv7IbN2yvLkTG3A=="
      - "KEYWORD_PATH=/porcupine/Alisa_en_linux_v2_2_0.ppn"
      - "LIB_PATH=/porcupine/libpv_porcupine_jni.so"
      - "MODEL_PATH=/porcupine/porcupine_params.pv"

      # ENABLING GUI
      - "DISPLAY=${DISPLAY}"
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - logs_db
    tty: true

  postgres:
    image: postgres
    volumes:
      - logs-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - '2345:5432'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=#{POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=logs-db'
    networks:
      - logs_db

volumes:
  logs-data:

networks:
  logs_db:
