version: '3.0'

services:
  postgres:
    image: postgres
    volumes:
      - logs-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - '2345:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=logs-db'

volumes:
  logs-data: