version: '3.0'

services:
  web-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/logs-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    devices:
      - /dev/snd:/dev/snd
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    volumes:
      - logs-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - '2345:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=logs-db'
    networks:
      - backend

volumes:
  logs-data:

networks:
  backend:
    driver: bridge