version: '3.0'

services:
  voice-gpt-app:
    image: voice-gpt-app
    container_name: voice-gpt-app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
        - /dev/snd:/dev/snd
    environment:
      - "GPT_HOST=localhost:8080"
      - "LISTENER_HOST=localhost:8081"
      - "GUI_HOST=localhost:8082"
      - "TTS_HOST=localhost:5001"
      - "STT_HOST=localhost:5000"
      - "POSTGRES_HOST=jdbc:postgresql://postgres:5432/logs-db"
      - "ACCESS_KEY=/QQF6ZXMMlgLz976gYguO5yIbgZH/89KbUpwq38/hKMA1BZbmv0ZyA=="
      - "KEYWORD_PATH=/porcupine/Alisa_en_linux_v2_2_0.ppn"
      - "LIB_PATH=/porcupine/libpv_porcupine_jni.so"
      - "MODEL_PATH=/porcupine/porcupine_params.pv"
      - "DISPLAY=${DISPLAY}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - logs_db

  postgres:
    image: postgres
    volumes:
      - logs-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - '2345:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=logs-db'
    networks:
      - logs_db

volumes:
  logs-data:

networks:
  logs_db:
