version: '3.0'

services:
#  web-app:
#    image: spring-app
#    container_name: spring-app
#    ports:
#      - "8080:8080"
#    networks:
#      - backend

  postgres:
    image: postgres
    volumes:
      - logs-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=logs-db'
    networks:
      - backend

volumes:
  logs-data:

networks:
  backend:
    driver: bridge