#----------PORCUPINE CONFIG-----------------------
porcupine:
  access-key: AFO98BBkrILaSbTEH109hZj5Fu0Bz+g1Zn3ssIUft4NtgHd/SjhlTw==
  library-path: /tmp/porcupine-java-2.1.4/porcupine/lib/java/linux/x86_64/libpv_porcupine_jni.so
  model-path: /tmp/porcupine-java-2.1.4/porcupine/lib/common/porcupine_params.pv
  keyword-paths: /home/abobus/Downloads/Alisa_en_linux_v2_1_0/Alisa_en_linux_v2_1_0.ppn
  sensitivities: 1