#---------------OPENAI API CONFIG---------------------
openai:
  token: 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
  duration:
    minutes: 5
    seconds: 0
  max_tokens: 2000
  model: text-davinci-003


#----------POSTGRES CONFIG-----------------------
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: password
    name: logs-db
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logs-db
