#---------------OPENAI API CONFIG---------------------
openai:
  token: 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
  duration:
    minutes: 5
    seconds: 0
  max_tokens: 2000
  model: text-davinci-003

#----------POSTGRES CONFIG-----------------------
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/logs-db

#----------PORCUPINE CONFIG-----------------------
porcupine:
  access-key: AFO98BBkrILaSbTEH109hZj5Fu0Bz+g1Zn3ssIUft4NtgHd/SjhlTw==
  library-path: /tmp/porcupine-java-2.1.4/porcupine/lib/java/linux/x86_64/libpv_porcupine_jni.so
  model-path: /tmp/porcupine-java-2.1.4/porcupine/lib/common/porcupine_params.pv
  keyword-paths: /home/abobus/Downloads/Alisa_en_linux_v2_1_0/Alisa_en_linux_v2_1_0.ppn
  sensitivities: 0.5