#---------------OPENAI API CONFIG---------------------
openai:
  token: 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
  duration:
    minutes: 5
    seconds: 0
  max_tokens: 2000
  model: text-davinci-003


#----------POSTGRES CONFIG-----------------------
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/logs-db
